#!/usr/bin/python
import xmlrpclib
import cPickle
from procxmlrpc.task import Task
import pwd, os

#print 'path:', path, 'user:', user
def submit (s, args, user, path, log_stdout, log_stderr):
    task_num = s.queue (args, user, {'path' : path}, log_stdout, log_stderr)
    return task_num

def get_status (s):
    active_tasks, queued_tasks, stopped_tasks = cPickle.loads (s.get_tasks())
    return active_tasks, queued_tasks, stopped_tasks

def run (cmdline):
    import argparse
    #from argparse_bool import ConfigureAction
    
    parser = argparse.ArgumentParser()
    parser.add_argument ('--submit', '-s', action='store_true')
    parser.add_argument ('--kill', type=int)
    parser.add_argument ('--stop', action='store_true')
    parser.add_argument ('--start', action='store_true')
    parser.add_argument ('--log-stdout')
    parser.add_argument ('--log-stderr')
    parser.add_argument ('--list', '-l', action='store_true')
    parser.add_argument ('--path')
    parser.add_argument ('--pidfile', default='/tmp/queue.pid')
    parser.add_argument ('--rundir')
    parser.add_argument ('--logfile', default='queue.log')
    parser.add_argument ('args', nargs='*')
    opt = parser.parse_args(cmdline)

    s = xmlrpclib.Server('http://localhost:7080/', allow_none=True)
    path = opt.path or os.getcwd()
    user = pwd.getpwuid(os.getuid())[0]

    ##print 'opt:', opt
    
    if opt.submit:
        task_num = submit (s, opt.args, user, path, opt.log_stdout, opt.log_stderr)
        print 'task_num:', task_num
        
    if opt.list:
        active_tasks, queued_tasks, stopped_tasks = get_status(s)
        print 'active:'
        for t in active_tasks:
            print t
        print 'queued:'
        for t in queued_tasks:
            print t

    if opt.kill:
        import signal
        s.kill (opt.kill, signal.SIGTERM)

    if opt.start:
        from twisted.scripts.twistd import run
        import sys
        sys.argv = ['twistd', '-y', 'server.tac', '--pidfile', opt.pidfile, '--logfile', opt.logfile]
        if opt.rundir:
            sys.argv += ['--rundir', opt.rundir]
        run()

    if opt.stop:
        import signal
        pid = int (open (opt.pidfile, 'r').readline())
        os.kill (pid, signal.SIGTERM)
        

if __name__ == '__main__':
    import sys
    run (sys.argv[1:])
